### ISSUE TITLE
Gambit for mac 

### ISSUE THREAD

**Issue by Maita93** [gambitproject/gte#38]
I am trying to download Gambit on my computer, which is a mac, and it doesn't work. It downloads but when I am trying to open it afterwards, it fails to open and signals an error. All the people who are using a mac in my class have the same problem (for any version of Gambit). Is there anything we can do to solve this problem and be able to use Gambit for our courses ?

**Comment by tturocy** [comment]
This issue tracker is for Game Theory Explorer, not Gambit.

Gambit is developed entirely on Mac and the binary is tested on everything from Mountain Lion forward, and runs successfully. If you are using something older then Mountain Lion, then that platform isn't supported. If you are on Mountain Lion or newer, then the issue is most likely something to do with your system, given that we have many reports of the binary working on those platforms (and none besides yours that it doesn't).  Absent more detail, this does not appear to be a Gambit issue, and regrettably we don't have the resources to troubleshoot individual users' own systems.
